CREATE TABLE IF NOT EXISTS admin (
  username TEXT PRIMARY KEY,
  password TEXT,
  nama TEXT
);

CREATE TABLE IF NOT EXISTS tendik (
  nip TEXT PRIMARY KEY,
  nama_tendik TEXT,
  password TEXT,
  jabatan TEXT
);

CREATE TABLE IF NOT EXISTS guru (
  nip TEXT PRIMARY KEY,
  nama_guru TEXT,
  password TEXT,
  target_jp INTEGER,
  mengajar TEXT,
  "No. Hp" TEXT
);

CREATE TABLE IF NOT EXISTS murid (
  "NISN" TEXT PRIMARY KEY,
  "Nama Lengkap" TEXT,
  "Kelas" TEXT,
  "Password (Default: baujeng(kelas))" TEXT,
  "Tanggal Lahir (YYYY-MM-DD)" TEXT,
  "Jenis Kelamin (L/P)" TEXT,
  "NIS" TEXT
);

CREATE TABLE IF NOT EXISTS jadwal_real (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hari TEXT,
  jam TEXT,
  kelas TEXT,
  mapel TEXT,
  guru TEXT,
  peran TEXT
);

CREATE TABLE IF NOT EXISTS jurnal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  nip TEXT,
  nama_guru TEXT,
  kelas TEXT,
  mata_pelajaran TEXT,
  jam_pembelajaran TEXT,
  materi TEXT,
  ketidakhadiran TEXT,
  catatan_mengajar TEXT,
  kebersihan_kelas TEXT,
  validasi TEXT,
  guru_piket_inval TEXT
);

CREATE TABLE IF NOT EXISTS presensi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  nip TEXT,
  nama_guru TEXT,
  nisn TEXT,
  nama_murid TEXT,
  kelas TEXT,
  presensi TEXT,
  ekstra TEXT
);

CREATE TABLE IF NOT EXISTS pengaturan (
  key TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS pengumuman (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal TIMESTAMPTZ DEFAULT NOW(),
  judul TEXT,
  isi TEXT,
  target_roles JSONB DEFAULT '["Publik"]'::jsonb,
  tanggal_terbit DATE,
  tanggal_kedaluwarsa DATE
);

CREATE TABLE IF NOT EXISTS testimoni (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  nama TEXT,
  lembaga TEXT,
  fitur TEXT,
  testimoni TEXT,
  rating INTEGER
);

CREATE TABLE IF NOT EXISTS helpdesk_config (
  key TEXT PRIMARY KEY,
  value JSONB
);

CREATE TABLE IF NOT EXISTS tabungan_sampah (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal TIMESTAMPTZ DEFAULT NOW(),
  siswa TEXT,
  kelas TEXT,
  jenis_sampah TEXT,
  berat NUMERIC,
  nilai NUMERIC
);

CREATE TABLE IF NOT EXISTS jenis_sampah (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama TEXT,
  harga NUMERIC
);

CREATE TABLE IF NOT EXISTS kasih_ibu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  nisn TEXT,
  nama_murid TEXT,
  kelas TEXT,
  jenis_kebiasaan TEXT,
  tanggal_kegiatan TEXT,
  waktu_kegiatan TEXT,
  keterangan TEXT,
  perasaan TEXT,
  validasi_walikelas TEXT DEFAULT 'Belum'
);

CREATE TABLE IF NOT EXISTS tugas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  teacher_id TEXT,
  guru_nama TEXT,
  kelas TEXT,
  mapel TEXT,
  judul TEXT,
  deskripsi TEXT,
  deadline TIMESTAMPTZ,
  target_students JSONB
);

CREATE TABLE IF NOT EXISTS pengumpulan_tugas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tugas_id BIGINT REFERENCES tugas(id) ON DELETE CASCADE,
  student_id TEXT,
  status TEXT,
  submitted_at TIMESTAMPTZ,
  content TEXT,
  validation_status TEXT,
  feedback TEXT
);

CREATE TABLE IF NOT EXISTS presensi_qr (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  nisn TEXT,
  nama TEXT,
  kelas TEXT,
  jenis TEXT,
  detail TEXT
);

-- Default Admin
-- INSERT INTO admin (username, password, nama) VALUES ('admin', 'admin@123', 'Administrator') ON CONFLICT DO NOTHING;
